CREATE TABLE IF NOT EXISTS material (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    material_key VARCHAR(500) NOT NULL UNIQUE,
    name VARCHAR(200) NOT NULL,
    spec VARCHAR(200),
    unit VARCHAR(50),
    current_qty DECIMAL(18,3) NOT NULL DEFAULT 0,
    last_price DECIMAL(18,4),
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS stock_movement (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    movement_type VARCHAR(3) NOT NULL,
    biz_date DATE NOT NULL,
    material_id BIGINT NOT NULL,
    material_name VARCHAR(200) NOT NULL,
    spec VARCHAR(200),
    unit VARCHAR(50),
    quantity DECIMAL(18,3) NOT NULL,
    unit_price DECIMAL(18,4),
    receiver VARCHAR(100),
    remark VARCHAR(500),
    source_key VARCHAR(128) UNIQUE,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_movement_material FOREIGN KEY(material_id) REFERENCES material(id),
    CONSTRAINT ck_movement_type CHECK (movement_type IN ('IN', 'OUT')),
    CONSTRAINT ck_movement_qty CHECK (quantity > 0)
);

CREATE INDEX IF NOT EXISTS idx_movement_date ON stock_movement(biz_date);
CREATE INDEX IF NOT EXISTS idx_movement_material ON stock_movement(material_id);
